spring:
  application:
    name: ediwriter
  codec:
    max-in-memory-size: 10MB
  zipkin:
    base-url: ${JAEGER_COLLECTOR_URL}
    service:
      name: ediwriter
    enabled: true 
  sleuth:
    opentracing:
      enabled: true   
    trace-id128: true
    sampler:
      probability: 1.0
      
server:
  port: 9305
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,env,httptrace,loggers

logging:
  level:
    ROOT: ERROR
    com.atd.microservices.core.ediwriter: DEBUG

apigateway:
  url: '${APIGATEWAY_URL}'
  
ediwriter:
  fusePath: /edi-outbound-files

